name: Build et push Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: recuperer le projet
        uses: actions/checkout@v4

      - name: connexion a Docker Hub
        uses: docker/login-action@v4
        with:
          username: patrice1607
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: construire l'image
        run: docker build -t patrice1607/go-api-rattrapage:latest .

      - name: envoyer l'image
        run: docker push patrice1607/go-api-rattrapage:latest

      - name: Deployer sur Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
